title: Ontimize Boot
description: Welcome to the Ontimize Boot v1.x.x documentation!
theme: just-the-docs
url: https://ontimize.github.io
logo: assets/icons/logo-ontimize-blanco.png
search_enabled: true
versions:
  - url: /docs/v1
    title: 1.x.x
    selected: true
  - url: /docs/v3
    title: 3.x.x
    selected: false
page_excerpts: true
github:
  - name: "Ontimize"
    url: https://github.com/Ontimize
    icon: assets/icons/github-front.svg
  # - name: "Ontimize Web"
  #   url: https://github.com/OntimizeWeb
  #   icon: assets/icons/github-front.svg
color_scheme: ontimize-light
callouts_level: quiet # or loud
callouts:
  highlight:
    color: grey-dk
  important:
    title: Important
    color: grey-dk
  note:
    title: Note
    color: blue
    opacity: 1
  warning:
    title: Warning
    color: red
